name: Create Next ABC Folder

on:
  schedule:
    - cron: '0 15 * * 5'  # 日本時間 土曜0時 = UTCで金曜15時
  workflow_dispatch:      # 手動実行も可

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate next ABC folder
        run: |
          python .github/scripts/create_next_abc.py

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ABC*
          git commit -m "Create next ABC folder" || echo "No changes to commit"
          git push
